# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MobileNuRemoter' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MobileNuRemoter
end

target 'NuRemoter' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  platform :osx, ’10.10’

  # Pods for NuRemoter
  pod 'CorePlot’, ‘~> 2.1’
end
